# Site settings
name: 成长日志
email: yl958623975@163.com
author: Yangl
github: https://github.com/yanglei1992/
description: study study study!
meta_description: 个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: 学如逆水行舟，不进则退.
banner: 学而不思则罔，思而不学则殆。

permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: yanglei1992


